services:
  synthetic-generator:
    profiles: ["gen"] # Gehört zum Profil 'gen'
    build:
      context: .
      dockerfile: generate_synthetic/Dockerfile
    container_name: synthetic_generator
    volumes:
      - ./object_images:/app/object_images
      - ./backgrounds:/app/backgrounds
      - ./dataset:/app/dataset
    command: ["python3", "generate_synthetic.py"]

  yolo-trainer:
    profiles: ["train"] # Gehört zum Profil 'train'
    build:
      context: .
      dockerfile: training/Dockerfile
    container_name: yolo_trainer
    volumes:
      - ./dataset:/usr/src/app/dataset
      - ./model:/usr/src/app/model
      - ./training:/usr/src/app/training
      - ./runs:/usr/src/app/runs
    command: ["python3", "training/train.py"]
    gpus: all
    shm_size: '8gb'

  yolo-detector:
      profiles: ["detect"]
      build:
        context: .
        dockerfile: detection/Dockerfile
      container_name: yolo_detector
      environment:
      - DISPLAY=host.docker.internal:0.0
      volumes:
        - ./dataset:/usr/src/app/dataset
        - .:/usr/src/app
        - ./model:/model
        - ./runs:/usr/src/app/runs
      command: ["python3", "detection/detection.py"]
      # --- RealSense & Hardware Zugriff --- 
      privileged: true  # Erleichtert den Zugriff auf USB-Busse erheblich
      devices:
        - "/dev/bus/usb:/dev/bus/usb" # Reicht den USB-Bus durch
      # ------------------------------------
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
      shm_size: '8gb'